# Generated by Django 3.2.3 on 2021-06-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210610_0601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
