# Generated by Django 3.2.3 on 2021-06-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210611_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('salary', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AddData',
        ),
    ]
